"""add spotify token fields to users

Revision ID: 341c58307386
Revises: a0edd7ff0fc9
Create Date: 2026-08-28 22:44:19.493833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341c58307386'
down_revision: Union[str, Sequence[str], None] = 'a0edd7ff0fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_token_expires_at')
    op.drop_column('users', 'spotify_refresh_token')
    op.drop_column('users', 'spotify_access_token')
    # ### end Alembic commands ###
