[project]
name = "melodex-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.31.0",
    "cryptography>=50.0.1",
    "fastapi[standard]>=0.128.8",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.2.1",
    "spotipy>=2.26.0",
    "sqlalchemy[asyncio]>=2.0.51",
    "uvicorn>=0.39.0",
]
